version: "3.4"

services:
  app_node_1:
    image: ricardomlima/blockchain-prototype
    volumes:
      - ./workplace:/home/
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
      MINER: "Ricardo"
    command: flask run --host=0.0.0.0

  app_node_2:
    image: ricardomlima/blockchain-prototype
    volumes:
      - ./workplace:/home/
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
      MINER: "Mariana"
    command: flask run --host=0.0.0.0 --port 5001

  app_node_3:
    image: ricardomlima/blockchain-prototype
    volumes:
      - ./workplace:/home/
    ports:
      - "5002:5002"
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
      MINER: "Rafael"
    command: flask run --host=0.0.0.0 --port 5002
